Todoリストの作成
nishimura-0615/react-todo-application pull request #2
Opened 2024-05-20 05:17 UTC by nishimura-0615

## 実装内容(What)

- reactのみで下記の機能を持ったTODOアプリを作成

    - Todo一覧表示
    -  Todo検索処理 (検索条件はタイトルの前方一致)
    - Todo追加処理
    - Todo削除処理

## 編集したこと(Why)

- `src/index.css `で画面や検索フォームで利用するフォントや背景色を編集

- ` react-todo/src/constants/data.js`で画面に出力させる初期データを作成

-  一覧表示するためのコンポーネント(`src/components/organisms/TodoLlist/TodoList.jsxTodoList.jsx)`を作成

- 追加、検索するためのフォームを作成(`src/components/atoms/InputForm/InputForm.jsx`)を作成

- 削除ボタンを作成

- それぞれのコンポーネントをスタイリングするためのCSSファイル(` style.module.css`)を作成

## バリデーションの有無
 - 特になし

## テスト証跡
- Todo一覧画面
<img width="1440" alt="スクリーンショット 2024-05-20 9 59 35" src="https://github.com/nishimura-0615/react-todo-application/assets/100144368/0ebc9626-0d01-4276-a2d4-2a4ba09d7751">

- Todo検索画面(検索条件はタイトルの前方一致)
<img width="1440" alt="スクリーンショット 2024-05-20 11 52 54" src="https://github.com/nishimura-0615/react-todo-application/assets/100144368/700d820a-d8c7-48c4-a47b-086b7103f24a">
<img width="1440" alt="スクリーンショット 2024-05-20 11 53 10" src="https://github.com/nishimura-0615/react-todo-application/assets/100144368/023f2e3e-9006-4d3b-aa00-bbcef7550a3a">

 - Todo追加処理
 
<img width="1440" alt="スクリーンショット 2024-05-20 14 13 25" src="https://github.com/nishimura-0615/react-todo-application/assets/100144368/54c92447-a6c2-4223-b3b9-ae00e3a8626e">
<img width="1440" alt="スクリーンショット 2024-05-20 14 13 31" src="https://github.com/nishimura-0615/react-todo-application/assets/100144368/9499531d-7c0b-4361-af9d-b97424b11625">

- Todo削除処理
  - 削除前

<img width="1440" alt="スクリーンショット 2024-05-20 13 42 05" src="https://github.com/nishimura-0615/react-todo-application/assets/100144368/4503a11f-66a4-4549-aa49-7219a7f47f8a">

 
- 削除後
<img width="1440" alt="スクリーンショット 2024-05-20 13 42 12" src="https://github.com/nishimura-0615/react-todo-application/assets/100144368/a80aa439-40ef-487d-a067-c1280da4735f">

 
## 再現手順

## レビュワーに考慮してほしいこと
 -` src/main.tsx`にて問題があったため、記述を変更しています。

## 補足
- 特になし

2024-05-20 07:52 UTC, Kohey-1642 requested changes
コメントしてます確認してください。
コード整形やpritterでやって自動保存を効かせてください。

2024-05-20 07:52 UTC, Kohey-1642 commented on react-todo/src/components/templates/TodoTemplate/TodoTemplate.jsx
> +export default TodoTemplate;
これいらない気がしますが・・

2024-05-20 07:52 UTC, Kohey-1642 commented on react-todo/src/components/templates/TodoTemplate/TodoTemplate.jsx
> +export const TodoTemplate = () => {
ファイル名index.jsxで良い気が（他も同様）

2024-05-20 07:52 UTC, Kohey-1642 commented on react-todo/src/components/templates/TodoTemplate/TodoTemplate.jsx
> +import { InputForm } from "../../atoms/InputForm/InputForm";
importとかはpritterを効かせたやり方でお願いします。
アルファベット順とかにしたほうがよい

2024-05-20 07:52 UTC, Kohey-1642 commented on react-todo/src/components/templates/TodoTemplate/TodoTemplate.jsx
> +
空白不要

2024-05-20 07:52 UTC, Kohey-1642 commented on react-todo/src/components/organisms/AddTodo/AddTodo.jsx
> +
ここも

2024-05-20 08:44 UTC, nishimura-0615 commented on react-todo/src/components/templates/TodoTemplate/TodoTemplate.jsx
> +export default TodoTemplate;
@Kohey-1642 該当の箇所の記述を削除しました。[1fa9ca9](https://github.com/nishimura-0615/react-todo-application/pull/2/commits/1fa9ca9dcc67641cf401944b8c5a2faf19d808c1)

2024-05-20 08:54 UTC, nishimura-0615 commented on react-todo/src/components/templates/TodoTemplate/TodoTemplate.jsx
> +export const TodoTemplate = () => {
@Kohey-1642 
ファイル名をindex.jsxに変更しました。[564404b](https://github.com/nishimura-0615/react-todo-application/pull/2/commits/564404bcdb16449b974df839827a1dd9dc25fe66)

2024-05-20 11:49 UTC, nishimura-0615 commented on react-todo/src/components/templates/TodoTemplate/TodoTemplate.jsx
> +import { InputForm } from "../../atoms/InputForm/InputForm";
prettierやeslintを設定してimportがソートできる様に修正しました。[4d523bc](https://github.com/nishimura-0615/react-todo-application/pull/2/commits/4d523bc7b43be139cf6b9122677c5014c093f0d5)

2024-05-20 12:00 UTC, nishimura-0615 commented on react-todo/src/components/templates/TodoTemplate/TodoTemplate.jsx
> +
@Kohey-1642 
不要な空行を削除しました。[77afa65](https://github.com/nishimura-0615/react-todo-application/pull/2/commits/77afa65058e6f90bd0feae5f72e96d74025b63b2)

2024-05-20 12:00 UTC, nishimura-0615 commented on react-todo/src/components/organisms/AddTodo/AddTodo.jsx
> +
@Kohey-1642 
不要な空行を削除しました。[77afa65](https://github.com/nishimura-0615/react-todo-application/pull/2/commits/77afa65058e6f90bd0feae5f72e96d74025b63b2)

2024-05-22 00:09 UTC, Kohey-1642 approved these changes

2024-05-22 00:16 UTC, merged