react routerを用いたSPAのTodoリスト
nishimura-0615/react-todo-application pull request #5
Opened 2024-05-27 08:26 UTC by nishimura-0615

2024-05-30 03:10 UTC, Kohey-1642 requested changes
とりあえず気になったところだけ

2024-05-30 03:10 UTC, Kohey-1642 commented on react-todo/src/components/atoms/InputForm/index.jsx
> +  const { disabled = false, value, placeholder, onChange, onKeyDown } = props;
pritter効いているなら改行されるはず

2024-05-30 03:10 UTC, Kohey-1642 commented on react-todo/src/components/organisms/TodoList/index.jsx
> +  return {
このretrun の意味は？？

2024-05-30 03:10 UTC, Kohey-1642 commented on react-todo/src/components/organisms/TodoList/index.jsx
> +  const { handleMoveDetailPage, handleMoveEditPage } = useTodoList();
useTodoListでわざわざやっているんですか？？
理由知りたいです

2024-05-30 03:10 UTC, Kohey-1642 commented on react-todo/src/components/templates/TodoCreateTemplate/index.jsx
> +  return {
この書き方はめっちゃ他の人が読みにくいアンチパターンの一つです。もしこれをやりたのであるなら別ファイルuseTodoCreateTemplate.jsに作成してからhandleChangeTitleなどを呼び出すほうが圧倒的に読みやすいです。

2024-05-31 01:55 UTC, nishimura-0615 commented on react-todo/src/components/atoms/InputForm/index.jsx
> +  const { disabled = false, value, placeholder, onChange, onKeyDown } = props;
@Kohey-1642 
InputFormを呼び出している箇所でpropsを渡していたのでpropsの定義は不要でした。[f46f107](https://github.com/nishimura-0615/react-todo-application/pull/5/commits/f46f1078260b13a89de0ea0e669248180d9cc98e)

2024-06-04 09:17 UTC, Kohey-1642 approved these changes
とりあえずOKです

2024-06-04 09:24 UTC, merged